Allow colon in locale message keys used in linked locale messages
kazupon/vue-i18n pull request #1488
Opened 2022-03-26 03:17 UTC by ax-jmckenzie

[Linked Locale Messages](https://kazupon.github.io/vue-i18n/guide/messages.html#formatting-linked-locale-messages)’ break when the linked locale message key contains a `:` character.  This updates a regex to allow for keys containing `:`, as long as the linked locale message uses the brackets syntax.

example:

```
{
  "homeAddress:phrase": "Home Address",
  "missingHomeAddress:validation": 'Please provide @.lower:(homeAddress:phrase)'
}
```

2022-03-27 16:10 UTC, kazupon requested changes
Thank you for your contribution!

Could you add the unit test cases, please? 🙏 
Our maintainers need to ensure that your updating works correctly.

2022-03-28 15:00 UTC, ax-jmckenzie commented
@kazupon, thanks for taking a look at this PR! I've added unit tests as requested.

2022-03-29 00:47 UTC, kazupon approved these changes

2022-03-29 00:48 UTC, kazupon commented
Thanks!
Good for your contribution! :)

2022-03-29 00:48 UTC, merged